# Generated by Django 2.2.1 on 2019-06-04 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyze', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='regress_invest',
            name='end_date',
            field=models.DateField(auto_now=True, verbose_name='结束时间'),
        ),
    ]
