# Generated by Django 2.2.1 on 2019-05-26 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='transation_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=20)),
                ('product_name', models.CharField(max_length=50)),
                ('transation_date', models.DateField()),
                ('transation_type', models.CharField(choices=[('SELL', '卖出'), ('BUY', '买入'), ('PROFITS', '分红')], default='SELL', max_length=10)),
            ],
        ),
    ]
